version: '3'
services:
  web:
    build: .
    command: gunicorn wordcount.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - CELERY_BROKER=redis://redis:6379/0
    depends_on:
      - redis
      - postgres

  

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: my_database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 33883246
    ports:
      - "5432:5432"

  celery:
    build: .
    command: celery -A wordcount worker --loglevel=info #--uid=myuser

    environment:
      - CELERY_BROKER=redis://redis:6379/0
    depends_on:
      - redis
