apiVersion: v1
kind: Service
metadata:
  name: django-service
  labels:
    app: django-app
spec:
  selector:
    app: django-app  # This ties the service to the pods with the label "app: django-app"
  ports:
    - protocol: TCP
      port: 80       # External port
      targetPort: 8000  # Container port
  type: ClusterIP  # Internal-only service
